name: Build and Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-tests:
    name: 'Run tests'
    runs-on: [ self-hosted, ex44 ]
    container: explyt/tsa-env:v1.1.0

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: 'Build tvm disasm'
        working-directory: ./tvm-disasm
        run: |
          npm i
          npm run build

      - name: 'Build and run test'
        run: gradle clean build
        env:
          TSA_RUN_HARD_TESTS: 1

      - name: 'Save test report'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ${{ github.workspace }}/**/build/reports/tests/
